import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import esbuildSvelte from "esbuild-svelte";
import { sveltePreprocess } from "svelte-preprocess";
import { copyFileSync, mkdirSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2022",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "dist/main.js",
  minify: prod,
  plugins: [
    esbuildSvelte({
      compilerOptions: { css: "injected" },
      preprocess: sveltePreprocess(),
    }),
  ],
});

// Ensure dist/ exists and copy static files
mkdirSync("dist", { recursive: true });

const filesToCopy = ["manifest.json", "styles.css"];
for (const file of filesToCopy) {
  try {
    copyFileSync(file, `dist/${file}`);
    console.log(`✓ Copied ${file} to dist/`);
  } catch (err) {
    if (file !== "styles.css") {
      console.warn(`⚠ Warning: Could not copy ${file}: ${err.message}`);
    }
  }
}

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
